---
title: "flow-analysis"
author: "Lakshmi Batachari"
date: "September 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(tidyverse)
theme_set(theme_classic())
```

```{r}
flow <- read_excel("Flow data/113018 Splenocytes FlowJo update.xls",sheet = 1)

meanValues <- flow %>%
  group_by(sampleName, baby) %>%
  summarize(Treg = mean(CD4_Foxp3_IL10), IL10 = mean(Live_IL10), CD4Foxp3 = mean(CD4_Foxp3))

meanValues$sampleName <- factor(meanValues$sampleName, levels = meanValues$sampleName[order(meanValues$baby)])

#IL10 fraction
ggplot(meanValues)+
  geom_bar(stat = "identity", aes(x = sampleName, y = IL10, fill = factor(baby)))+
  xlab("Bacterial Product") +
  ylab("IL10+ Fraction") +
  theme(axis.text.x = element_text(hjust = 1, size =6, angle = 90), axis.text.y = element_text(size = 6))+
  scale_fill_discrete(name = "Baby")

#CD4+Foxp3+ fraction
ggplot(meanValues)+
  geom_bar(stat = "identity", aes(x = sampleName, y = CD4Foxp3, fill = factor(baby)))+
  xlab("Bacterial Product") +
  ylab("CD4+Foxp3+ Fraction") +
  theme(axis.text.x = element_text(hjust = 1, size =6, angle = 90), axis.text.y = element_text(size = 6))+
  scale_fill_discrete(name = "Baby")

#CD4+Foxp3+IL10+ fraction
ggplot(meanValues)+
  geom_bar(stat = "identity", aes(x = sampleName, y = Treg, fill = factor(baby)))+
  xlab("Bacterial Product") +
  ylab("CD4+Foxp3+IL10+ Fraction") +
  theme(axis.text.x = element_text(hjust = 1, size =6, angle = 90), axis.text.y = element_text(size = 6))+
  scale_fill_discrete(name = "Baby")

```

Hannah's data
```{r}

HCC <- read_excel("Flow data/121018 Splenocytes HCC modified.xls", sheet = 1)

HCCmeanValues <- HCC %>%
  group_by(sampleName) %>%
  summarize(Treg = mean(CD4_Foxp3_IL10), IL10 = mean(Live_IL10), CD4Foxp3 = mean(CD4_Foxp3))

ggplot(HCCmeanValues) +
  geom_bar(stat = "identity", aes(x = sampleName, y = IL10))+
  xlab("Bacterial Product") +
  ylab("IL10+ Fraction") +
  theme(axis.text.x = element_text(hjust = 1, size =10, angle = 90), axis.text.y = element_text(size = 6))

ggplot(HCCmeanValues) +
  geom_bar(stat = "identity", aes(x = sampleName, y = CD4Foxp3))+
  xlab("Bacterial Product") +
  ylab("CD4+Foxp3+ Fraction") +
  theme(axis.text.x = element_text(hjust = 1, size =10, angle = 90), axis.text.y = element_text(size = 6))

ggplot(HCCmeanValues) +
  geom_bar(stat = "identity", aes(x = sampleName, y = Treg))+
  xlab("Bacterial Product") +
  ylab("CD4+Foxp3+IL10+ Fraction") +
  theme(axis.text.x = element_text(hjust = 1, size =10, angle = 90), axis.text.y = element_text(size = 6))
```

```{r}
#CD4+Foxp3+ fraction
ggplot(meanValues)+
  geom_bar(stat = "identity", aes(x = sampleName, y = CD4Foxp3, fill = factor(baby)))+
  xlab("Bacterial Product") +
  ylab("CD4+Foxp3+ Fraction") +
  theme(axis.text.x = element_text(hjust = 1, size =6, angle = 90), axis.text.y = element_text(size = 6))+
  scale_fill_discrete(name = "Baby")

CD4Foxp3 = mean(CD4_Foxp3)

```
